####
# ATENTION:
# Replace all occurences of sandbox with your project's name
####

# v2 syntax
version: '3'

services:
  # Postgres (9.5)

  mysql:
    image: mysql:5.7
    container_name: sandbox-mysql
    volumes:
      - ./storage/myslq:/var/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=sandbox
      - MYSQL_DATABASE=sandbox
      - MYSQL_USER=sandbox
      - MYSQL_PASSWORD=sandbox


  # PHP (with Caddy)
  app:
    image: ambientum/php:7.3-nginx
    container_name: sandbox-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
